name: Test and run
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release-to-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and build dependencies
        run: |
          sed -i "s#echo '\(.\+\)' &&#\1 \&\&#" package.json
          npm install -g yarn
          yarn install
          yarn build

      - name: Configuring deployment to production
        run: |
          echo "Deploying to production"
          pwd
          chmod +x ./deploy.sh
          ./deploy.sh

      - name: deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: release
          folder: dist
