name: Test and run
on:
  workflow_dispatch:
  push:
    branches:
    - main
    
jobs: 
  test-node-compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install and build
        run: |
          npm install -g yarn
          yarn 
          yarn wpack
          yarn build
          cp package.json yarn.lock dist/
      - name: deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: release
          folder: dist
      
      
      
